/**
 * audit.js — SR&ED Audit Package PDF
 *
 * POST /api/v1/audit/pdf
 *   Accepts scan data + CCPC/province params, returns a multi-page
 *   audit-ready PDF generated by server/scripts/audit_pdf.py via ReportLab.
 *   No auth required — used from the free scan funnel and the dashboard.
 *
 * Body: {
 *   repos, clusters, credit, creditLow, creditHigh,
 *   commitCount, hoursTotal, isCcpc, province, email
 * }
 */

const express     = require('express')
const router      = express.Router()
const { spawn }   = require('child_process')
const path        = require('path')

const SCRIPT = path.join(__dirname, '../scripts/audit_pdf.py')

router.post('/pdf', (req, res) => {
  const body = req.body
  if (!body || !body.clusters) {
    return res.status(400).json({ error: 'clusters array required' })
  }

  const payload = JSON.stringify({
    repos:        body.repos        ?? [],
    clusters:     body.clusters     ?? [],
    credit:       body.credit       ?? 0,
    creditLow:    body.creditLow    ?? Math.round((body.credit ?? 0) * 0.65),
    creditHigh:   body.creditHigh   ?? Math.round((body.credit ?? 0) * 1.35),
    commitCount:  body.commitCount  ?? 0,
    hoursTotal:   body.hoursTotal   ?? 0,
    isCcpc:       body.isCcpc       ?? true,
    province:     body.province     ?? 'ON',
    email:        body.email        ?? '',
    generatedAt:  new Date().toISOString().slice(0, 10),
  })

  const py = spawn('python3', [SCRIPT])

  const chunks = []
  let   stderr = ''

  py.stdin.write(payload)
  py.stdin.end()

  py.stdout.on('data', chunk => chunks.push(chunk))
  py.stderr.on('data', d    => { stderr += d.toString() })

  py.on('close', code => {
    if (code !== 0) {
      console.error('[audit/pdf] python exited', code, stderr)
      return res.status(500).json({ error: 'PDF generation failed', detail: stderr.slice(0, 300) })
    }
    const pdf = Buffer.concat(chunks)
    const company = (body.repos?.[0] ?? 'company').split('/')[0]
    const filename = `taxlift-sred-audit-${company}-${new Date().toISOString().slice(0,10)}.pdf`
    res.set({
      'Content-Type':        'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length':      pdf.length,
    })
    res.end(pdf)
  })

  py.on('error', err => {
    console.error('[audit/pdf] spawn error', err)
    res.status(500).json({ error: 'Could not start PDF generator' })
  })
})

module.exports = router
