/**
 * CpaReviewPage — /cpa-review/:token
 *
 * Public, read-only view for CPAs. No login required.
 * Decodes the token generated by ShareWithCpaModal and renders:
 *   1. Header with company / fiscal year / expiry notice
 *   2. Key metrics hero (credit, hours, audit score, clusters)
 *   3. T661 financial schedule estimate
 *   4. SR&ED project narratives (expandable per cluster)
 *   5. Evidence integrity table
 *   6. "Request access / Book a review" CTA
 */
import { useState, useMemo } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  ShieldCheck, Clock, DollarSign, FileText, Layers,
  ChevronDown, ChevronUp, AlertTriangle, CheckCircle2,
  Calendar, Lock, Users, Mail, ExternalLink, Info,
  BarChart2, Shield, AlertCircle, GitMerge,
} from 'lucide-react'
import { decodeCpaToken, isTokenExpired, daysUntilExpiry } from '../lib/cpaToken'

// ── Formatting helpers ────────────────────────────────────────────────────────
const fmt = (n) =>
  n != null
    ? new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD', maximumFractionDigits: 0 }).format(n)
    : '—'

const fmtHours = (h) => h != null ? `${Number(h).toFixed(1)} h` : '—'

const fmtDate = (d) =>
  d ? new Date(d).toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' }) : '—'

const fmtDateTime = (d) =>
  d ? new Date(d).toLocaleString('en-CA', { dateStyle: 'medium', timeStyle: 'short' }) : '—'

function fmtPercent(n) {
  if (n == null) return '—'
  return `${(n * 100).toFixed(0)}%`
}

// ── Risk badge ────────────────────────────────────────────────────────────────
function RiskBadge({ score }) {
  if (score == null) return <span className="text-xs text-gray-400">—</span>
  const pct  = Math.round(score * 100)
  const color = pct >= 80 ? 'text-red-600 bg-red-50' : pct >= 60 ? 'text-amber-600 bg-amber-50' : 'text-green-600 bg-green-50'
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold ${color}`}>
      {pct}% risk
    </span>
  )
}

// ── Cluster card ──────────────────────────────────────────────────────────────
function ClusterCard({ cluster, index }) {
  const [expanded, setExpanded] = useState(false)
  const hasNarrative = !!(cluster.narrative)

  return (
    <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden">
      {/* Header row */}
      <button
        className="w-full flex items-start gap-4 px-5 py-4 text-left hover:bg-gray-50 transition-colors"
        onClick={() => setExpanded(v => !v)}
      >
        <div className="w-7 h-7 rounded-lg bg-indigo-50 flex items-center justify-center flex-shrink-0 mt-0.5">
          <span className="text-xs font-bold text-indigo-600">{index + 1}</span>
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-gray-900 leading-snug">{cluster.name}</p>
          <div className="flex items-center gap-3 mt-1.5 flex-wrap">
            <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-green-100 text-green-700 text-xs font-medium rounded-full">
              <CheckCircle2 size={10} /> {cluster.status}
            </span>
            {cluster.hours != null && (
              <span className="text-xs text-gray-500">{fmtHours(cluster.hours)}</span>
            )}
            {cluster.creditCAD != null && (
              <span className="text-xs font-semibold text-emerald-700">{fmt(cluster.creditCAD)}</span>
            )}
            <RiskBadge score={cluster.riskScore} />
            {hasNarrative
              ? <span className="text-xs text-indigo-600 font-medium">Narrative ready</span>
              : <span className="text-xs text-amber-600">No narrative</span>}
          </div>
        </div>
        <div className="flex-shrink-0 mt-1 text-gray-400">
          {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </div>
      </button>

      {/* Expanded narrative */}
      {expanded && (
        <div className="border-t border-gray-100 px-5 py-4 space-y-4">
          {/* Evidence reference */}
          {cluster.evidenceSnapshotId && (
            <div className="flex items-center gap-2 text-xs text-gray-500">
              <Shield size={12} className="text-indigo-500 flex-shrink-0" />
              <span>Evidence snapshot: </span>
              <span className="font-mono text-gray-700">{cluster.evidenceSnapshotId}</span>
              <span className="ml-1 px-1.5 py-0.5 bg-green-100 text-green-700 rounded font-medium">✓ Verified</span>
            </div>
          )}

          {/* Narrative */}
          {hasNarrative ? (
            <div>
              <div className="flex items-center gap-2 mb-2">
                <FileText size={12} className="text-indigo-500" />
                <p className="text-xs font-semibold text-gray-700 uppercase tracking-wide">T661 Narrative (Part 2)</p>
                {cluster.narrativeApproved && (
                  <span className="px-1.5 py-0.5 bg-green-100 text-green-700 text-[10px] font-semibold rounded-full">Approved</span>
                )}
              </div>
              <div className="bg-gray-50 border border-gray-100 rounded-xl p-4 text-xs text-gray-700 leading-relaxed whitespace-pre-wrap font-sans">
                {cluster.narrative}
              </div>
            </div>
          ) : (
            <div className="flex items-start gap-2 bg-amber-50 border border-amber-200 rounded-xl px-3.5 py-3 text-xs text-amber-800">
              <AlertTriangle size={13} className="text-amber-500 flex-shrink-0 mt-0.5" />
              <p>No narrative available for this project yet. The company needs to generate one in TaxLift before finalising the package.</p>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ── T661 schedule section ─────────────────────────────────────────────────────
function T661Section({ t661 }) {
  if (!t661) return null

  const rows = [
    { line: '100', desc: 'SR&ED salaries and wages',                        value: t661.line100 },
    { line: '200', desc: 'Prescribed Proxy Amount (55% × Line 100)',        value: t661.line200 },
    { line: '300', desc: 'SR&ED contracts (third-party)',                   value: t661.line300 },
    { line: '400', desc: 'Total qualified SR&ED expenditures',              value: t661.line400, bold: true },
    { line: '500', desc: 'Pool of deductible SR&ED expenditures',           value: t661.line500 },
  ]

  return (
    <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-100">
        <div className="flex items-center gap-2">
          <BarChart2 size={15} className="text-indigo-600" />
          <h2 className="text-sm font-bold text-gray-900">T661 Financial Schedule (Estimated)</h2>
        </div>
        <p className="text-xs text-gray-500 mt-1">
          {t661.entityType ?? 'CCPC'} · Proxy method (Prescribed Proxy Amount) · For review only
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-100">
              <th className="px-5 py-2.5 text-left text-[10px] font-semibold text-gray-500 uppercase tracking-wider w-16">Line</th>
              <th className="px-5 py-2.5 text-left text-[10px] font-semibold text-gray-500 uppercase tracking-wider">Description</th>
              <th className="px-5 py-2.5 text-right text-[10px] font-semibold text-gray-500 uppercase tracking-wider w-36">Amount (CAD)</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {rows.map(row => (
              <tr key={row.line} className={row.bold ? 'bg-indigo-50' : 'hover:bg-gray-50'}>
                <td className="px-5 py-2.5 text-xs font-mono text-gray-500">{row.line}</td>
                <td className={`px-5 py-2.5 text-sm ${row.bold ? 'font-semibold text-gray-900' : 'text-gray-700'}`}>
                  {row.desc}
                </td>
                <td className={`px-5 py-2.5 text-right tabular-nums ${row.bold ? 'font-bold text-indigo-700' : 'text-gray-700'}`}>
                  {fmt(row.value)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ITC */}
      <div className="px-6 py-4 border-t border-gray-100 bg-emerald-50">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold text-gray-700">
              Estimated Investment Tax Credit (ITC)
              {t661.isCCPC ? ' — Refundable (CCPC)' : ' — Non-refundable'}
            </p>
            {t661.isCCPC && (
              <p className="text-[11px] text-gray-500 mt-0.5">
                First {fmt(t661.firstBracket)} × 35%
                {t661.secondBracket > 0 && ` + ${fmt(t661.secondBracket)} × 15%`}
              </p>
            )}
          </div>
          <p className="text-2xl font-bold text-emerald-700 tabular-nums">{fmt(t661.itc)}</p>
        </div>
      </div>

      <div className="px-5 py-3 bg-amber-50 border-t border-amber-100">
        <p className="text-[11px] text-amber-800 flex items-start gap-1.5">
          <Info size={11} className="flex-shrink-0 mt-0.5 text-amber-500" />
          These are pre-filing estimates for review only. Your firm must verify and adjust all figures before filing the T661 with the T2 corporate return. TaxLift does not file with the CRA.
        </p>
      </div>
    </div>
  )
}

// ── Audit readiness ring ───────────────────────────────────────────────────────
function AuditScoreRing({ score }) {
  const r   = 36
  const circ = 2 * Math.PI * r
  const dash = Math.min(1, score / 100) * circ
  const color = score >= 75 ? '#22c55e' : score >= 50 ? '#f59e0b' : '#ef4444'
  return (
    <svg width={96} height={96} viewBox="0 0 96 96">
      <circle cx={48} cy={48} r={r} fill="none" stroke="#e5e7eb" strokeWidth={8} />
      <circle
        cx={48} cy={48} r={r} fill="none"
        stroke={color} strokeWidth={8}
        strokeDasharray={`${dash} ${circ}`}
        strokeLinecap="round"
        transform="rotate(-90 48 48)"
      />
      <text x={48} y={53} textAnchor="middle" fontSize={18} fontWeight={700} fill={color}>{score}</text>
    </svg>
  )
}

// ── Evidence table ─────────────────────────────────────────────────────────────
function EvidenceSection({ clusters }) {
  const withEvidence = clusters.filter(c => c.evidenceSnapshotId)
  if (withEvidence.length === 0) return null

  return (
    <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-100 flex items-center gap-2">
        <Shield size={15} className="text-indigo-600" />
        <h2 className="text-sm font-bold text-gray-900">Evidence Chain of Custody</h2>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-100">
              {['SR&ED Project', 'Evidence Type', 'Snapshot ID', 'Integrity'].map(h => (
                <th key={h} className="px-5 py-2.5 text-left text-[10px] font-semibold text-gray-500 uppercase tracking-wider">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {clusters.map((c, i) => (
              <tr key={i} className="hover:bg-gray-50">
                <td className="px-5 py-3 text-sm font-medium text-gray-900 max-w-xs truncate">{c.name}</td>
                <td className="px-5 py-3 text-xs text-gray-500">Git · Jira · CI/CD</td>
                <td className="px-5 py-3 font-mono text-xs text-gray-600">
                  {c.evidenceSnapshotId ?? <span className="text-gray-300">—</span>}
                </td>
                <td className="px-5 py-3">
                  {c.evidenceSnapshotId
                    ? <span className="inline-flex items-center gap-1 text-xs text-green-700 font-medium"><CheckCircle2 size={11} /> Verified</span>
                    : <span className="inline-flex items-center gap-1 text-xs text-amber-600 font-medium"><AlertTriangle size={11} /> Missing</span>
                  }
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ── Request access CTA ─────────────────────────────────────────────────────────
function CpaCtaSection({ sharedByEmail, companyName }) {
  const [name,    setName]    = useState('')
  const [email,   setEmail]   = useState('')
  const [firm,    setFirm]    = useState('')
  const [message, setMessage] = useState('')
  const [sent,    setSent]    = useState(false)

  function handleSubmit(e) {
    e.preventDefault()
    // In production: POST to API. For MVP: just show success state.
    setSent(true)
  }

  if (sent) {
    return (
      <div className="bg-green-50 border border-green-200 rounded-2xl px-6 py-8 text-center">
        <CheckCircle2 size={32} className="text-green-500 mx-auto mb-3" />
        <p className="text-base font-bold text-green-900">Request sent!</p>
        <p className="text-sm text-green-700 mt-1 max-w-sm mx-auto">
          {companyName}'s team has been notified. They'll reach out to arrange a review call.
        </p>
      </div>
    )
  }

  return (
    <div className="bg-gradient-to-br from-slate-900 to-indigo-900 rounded-2xl overflow-hidden">
      <div className="px-6 py-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center">
            <Mail size={18} className="text-white" />
          </div>
          <div>
            <p className="text-white font-bold text-base">Ready to review this claim?</p>
            <p className="text-indigo-200 text-xs mt-0.5">
              Request access to the full platform or book a review call with {companyName}'s team.
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-medium text-indigo-200 mb-1">Your name</label>
              <input
                type="text"
                value={name}
                onChange={e => setName(e.target.value)}
                required
                placeholder="Jane Smith, CPA"
                className="w-full bg-white/10 border border-white/20 rounded-lg px-3 py-2 text-sm text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-indigo-400"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-indigo-200 mb-1">Your firm</label>
              <input
                type="text"
                value={firm}
                onChange={e => setFirm(e.target.value)}
                placeholder="Crowe MacKay LLP"
                className="w-full bg-white/10 border border-white/20 rounded-lg px-3 py-2 text-sm text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-indigo-400"
              />
            </div>
          </div>
          <div>
            <label className="block text-xs font-medium text-indigo-200 mb-1">Your email</label>
            <input
              type="email"
              value={email}
              onChange={e => setEmail(e.target.value)}
              required
              placeholder="jane.smith@firm.ca"
              className="w-full bg-white/10 border border-white/20 rounded-lg px-3 py-2 text-sm text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-indigo-400"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-indigo-200 mb-1">Message (optional)</label>
            <textarea
              value={message}
              onChange={e => setMessage(e.target.value)}
              rows={2}
              placeholder="Questions about the claim, availability for a review call, etc."
              className="w-full bg-white/10 border border-white/20 rounded-lg px-3 py-2 text-sm text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"
            />
          </div>
          <button
            type="submit"
            className="w-full bg-white text-indigo-700 font-bold py-2.5 rounded-xl text-sm hover:bg-indigo-50 transition-colors mt-1"
          >
            Send request to {companyName}'s team
          </button>
        </form>

        {sharedByEmail && (
          <p className="text-center text-xs text-indigo-300 mt-3">
            Alternatively, email directly: <a href={`mailto:${sharedByEmail}`} className="underline hover:text-white">{sharedByEmail}</a>
          </p>
        )}
      </div>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────
export default function CpaReviewPage() {
  const { token }   = useParams()
  const navigate    = useNavigate()

  const payload = useMemo(() => decodeCpaToken(token ?? ''), [token])
  const expired = payload ? isTokenExpired(payload) : false
  const daysLeft = payload ? daysUntilExpiry(payload) : null

  // ── Invalid token ──
  if (!payload) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6">
        <div className="text-center max-w-sm">
          <div className="w-16 h-16 rounded-2xl bg-red-100 flex items-center justify-center mx-auto mb-4">
            <AlertCircle size={28} className="text-red-500" />
          </div>
          <h1 className="text-xl font-bold text-gray-900 mb-2">Invalid review link</h1>
          <p className="text-sm text-gray-500 mb-6">This link is invalid or has been corrupted. Please ask the sender to generate a new one from TaxLift.</p>
          <button onClick={() => navigate('/')} className="px-4 py-2 bg-indigo-600 text-white text-sm font-semibold rounded-lg hover:bg-indigo-700">
            Go to TaxLift
          </button>
        </div>
      </div>
    )
  }

  const {
    companyName, fiscalYear, filingDeadline, auditScore,
    totalCredit, totalHours, sharedBy, sharedByEmail,
    generatedAt, expiresAt, t661, clusters = [], clusterTotals,
  } = payload

  const auditChecklist = [
    { label: 'Evidence captured & hashed',   done: auditScore >= 40 },
    { label: 'T661 narratives drafted',       done: auditScore >= 60 },
    { label: 'Developer interviews complete', done: auditScore >= 75 },
    { label: 'CPA review package ready',      done: auditScore >= 90 },
  ]

  return (
    <div className="min-h-screen bg-gray-50">

      {/* ── Top bar ── */}
      <div className="bg-slate-900 border-b border-slate-800 px-6 py-3 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-7 h-7 bg-indigo-500 rounded-lg flex items-center justify-center">
            <ShieldCheck size={14} className="text-white" />
          </div>
          <span className="text-white font-bold text-sm tracking-tight">TaxLift</span>
          <span className="hidden sm:block text-slate-500 text-xs">|</span>
          <span className="hidden sm:block text-slate-400 text-xs">SR&ED CPA Review Package</span>
        </div>
        <div className="flex items-center gap-2">
          <Lock size={11} className="text-slate-500" />
          <span className="text-slate-400 text-xs">Read-only · No login required</span>
        </div>
      </div>

      {/* ── Expiry banner ── */}
      {expired ? (
        <div className="bg-red-600 px-6 py-2.5 text-center">
          <p className="text-white text-xs font-semibold">
            This review link has expired. Please ask {companyName} to generate a new one from TaxLift.
          </p>
        </div>
      ) : daysLeft != null && daysLeft <= 2 ? (
        <div className="bg-amber-500 px-6 py-2.5 text-center">
          <p className="text-white text-xs font-semibold">
            This link expires {daysLeft === 0 ? 'today' : `in ${daysLeft} day${daysLeft !== 1 ? 's' : ''}`} · {fmtDate(expiresAt)}
          </p>
        </div>
      ) : null}

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-6">

        {/* ── Company hero ── */}
        <div className="bg-gradient-to-r from-slate-800 to-indigo-900 rounded-2xl px-6 py-6">
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <p className="text-indigo-300 text-xs font-semibold uppercase tracking-wider mb-1">SR&ED Claim · CPA Review</p>
              <h1 className="text-2xl font-bold text-white">{companyName}</h1>
              <p className="text-indigo-200 text-sm mt-1">Fiscal Year {fiscalYear}</p>
              {filingDeadline && (
                <div className="flex items-center gap-1.5 mt-2 text-indigo-200 text-xs">
                  <Calendar size={11} />
                  T2 Filing Deadline: {fmtDate(filingDeadline)}
                </div>
              )}
            </div>
            <div className="text-right">
              <p className="text-indigo-300 text-xs mb-0.5">Prepared by</p>
              <p className="text-white text-sm font-semibold">{sharedBy}</p>
              {sharedByEmail && <p className="text-indigo-300 text-xs mt-0.5">{sharedByEmail}</p>}
              <p className="text-indigo-400 text-[11px] mt-2">Generated {fmtDateTime(generatedAt)}</p>
              {expiresAt && (
                <div className="inline-flex items-center gap-1 mt-1.5 px-2 py-1 bg-white/10 rounded-lg text-indigo-200 text-[11px]">
                  <Clock size={10} />
                  Expires {fmtDate(expiresAt)}
                </div>
              )}
            </div>
          </div>

          {/* Key metrics */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5">
            {[
              { label: 'Estimated Credit', value: fmt(totalCredit),         icon: DollarSign, color: 'text-emerald-300' },
              { label: 'Eligible Hours',   value: fmtHours(totalHours),     icon: Clock,      color: 'text-blue-300'    },
              { label: 'Clusters',         value: clusterTotals ? `${clusterTotals.approved} / ${clusterTotals.total}` : clusters.length, icon: GitMerge, color: 'text-indigo-300' },
              { label: 'Audit Readiness',  value: auditScore != null ? `${auditScore}/100` : '—', icon: ShieldCheck, color: 'text-green-300' },
            ].map(item => (
              <div key={item.label} className="bg-white/10 rounded-xl px-4 py-3">
                <div className="flex items-center gap-1.5 mb-1">
                  <item.icon size={12} className={item.color} />
                  <p className="text-[10px] text-white/60 uppercase tracking-wider">{item.label}</p>
                </div>
                <p className="text-xl font-bold text-white tabular-nums">{item.value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ── Audit readiness ── */}
        <div className="bg-white rounded-2xl border border-gray-200 px-6 py-5">
          <div className="flex items-center gap-2 mb-4">
            <ShieldCheck size={15} className="text-indigo-600" />
            <h2 className="text-sm font-bold text-gray-900">Audit Readiness</h2>
            <span className={`ml-auto text-sm font-bold ${auditScore >= 75 ? 'text-green-700' : auditScore >= 50 ? 'text-amber-600' : 'text-red-600'}`}>
              {auditScore}/100
            </span>
          </div>
          <div className="flex items-start gap-6">
            <AuditScoreRing score={auditScore ?? 0} />
            <div className="flex-1 space-y-2.5 pt-1">
              {auditChecklist.map((item, i) => (
                <div key={i} className="flex items-center gap-2.5 text-sm">
                  <div className={`w-4 h-4 rounded-full flex items-center justify-center flex-shrink-0 ${item.done ? 'bg-green-500' : 'bg-gray-200'}`}>
                    {item.done && (
                      <svg width={8} height={8} viewBox="0 0 8 8" fill="none">
                        <path d="M1.5 4L3 5.5L6.5 2" stroke="white" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    )}
                  </div>
                  <span className={item.done ? 'text-gray-800' : 'text-gray-400'}>{item.label}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── T661 schedule ── */}
        <T661Section t661={t661} />

        {/* ── SR&ED projects ── */}
        <div>
          <div className="flex items-center gap-2 mb-3">
            <Layers size={15} className="text-indigo-600" />
            <h2 className="text-sm font-bold text-gray-900">
              SR&ED Projects ({clusters.length} cluster{clusters.length !== 1 ? 's' : ''})
            </h2>
            <span className="ml-2 text-xs text-gray-500">Click a project to view narrative</span>
          </div>

          {clusters.length === 0 ? (
            <div className="bg-gray-50 border border-dashed border-gray-200 rounded-2xl py-12 text-center">
              <Layers size={24} className="text-gray-300 mx-auto mb-2" />
              <p className="text-sm text-gray-400">No approved clusters in this package.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {clusters.map((cluster, i) => (
                <ClusterCard key={cluster.id ?? i} cluster={cluster} index={i} />
              ))}
            </div>
          )}
        </div>

        {/* ── Evidence chain of custody ── */}
        <EvidenceSection clusters={clusters} />

        {/* ── CPA action CTA ── */}
        <CpaCtaSection sharedByEmail={sharedByEmail} companyName={companyName} />

        {/* ── Footer ── */}
        <div className="text-center pb-6">
          <div className="flex items-center justify-center gap-2 mb-3">
            <div className="w-6 h-6 bg-indigo-500 rounded-md flex items-center justify-center">
              <ShieldCheck size={13} className="text-white" />
            </div>
            <span className="text-sm font-bold text-gray-700">TaxLift</span>
          </div>
          <p className="text-xs text-gray-400 max-w-lg mx-auto leading-relaxed">
            This package was prepared using the TaxLift SR&ED compliance platform. All credit
            amounts are preliminary estimates for CPA review only. A qualified SR&ED tax specialist
            must review, adjust, and confirm all figures — and is solely responsible for filing the
            T661 with the T2 corporate return. TaxLift is a preparation and documentation tool.
            It does not file with the CRA on your behalf.
          </p>
        </div>
      </div>
    </div>
  )
}
